require 'Items/ProceduralDistributions'

-- Debug Mode
-- table.insert(ProceduralDistributions.list["BookstoreBooks"].items, "ImprovisedFlooring.IFMagazineTiles1");
-- table.insert(ProceduralDistributions.list["BookstoreBooks"].items, 1000);
-- table.insert(ProceduralDistributions.list["BookstoreBooks"].items, "ImprovisedFlooring.IFMagazineTiles2");
-- table.insert(ProceduralDistributions.list["BookstoreBooks"].items, 1000);
-- table.insert(ProceduralDistributions.list["BookstoreBooks"].items, "ImprovisedFlooring.IFMagazineTiles3");
-- table.insert(ProceduralDistributions.list["BookstoreBooks"].items, 1000);
-- table.insert(ProceduralDistributions.list["BookstoreBooks"].items, "ImprovisedFlooring.IFMagazineWood1");
-- table.insert(ProceduralDistributions.list["BookstoreBooks"].items, 1000);
-- table.insert(ProceduralDistributions.list["BookstoreBooks"].items, "ImprovisedFlooring.IFMagazineCarpet1");
-- table.insert(ProceduralDistributions.list["BookstoreBooks"].items, 1000);
-- table.insert(ProceduralDistributions.list["BookstoreBooks"].items, "ImprovisedFlooring.IFMagazineSpecial1");
-- table.insert(ProceduralDistributions.list["BookstoreBooks"].items, 1000);
-- table.insert(ProceduralDistributions.list["BookstoreBooks"].items, "ImprovisedFlooring.IFMagazineSpecial2");
-- table.insert(ProceduralDistributions.list["BookstoreBooks"].items, 1000);
-- table.insert(ProceduralDistributions.list["BookstoreBooks"].items, "ImprovisedFlooring.IFMagazineSpecial3");
-- table.insert(ProceduralDistributions.list["BookstoreBooks"].items, 1000);

-- Carpet 1
table.insert(ProceduralDistributions.list["BookstoreMisc"].items, "ImprovisedFlooring.IFMagazineCarpet1");
table.insert(ProceduralDistributions.list["BookstoreMisc"].items, 3);
table.insert(ProceduralDistributions.list["CrateBooks"].items, "ImprovisedFlooring.IFMagazineCarpet1");
table.insert(ProceduralDistributions.list["CrateBooks"].items, 6);
table.insert(ProceduralDistributions.list["CrateMagazines"].items, "ImprovisedFlooring.IFMagazineCarpet1");
table.insert(ProceduralDistributions.list["CrateMagazines"].items, 1);
table.insert(ProceduralDistributions.list["DeskGeneric"].items, "ImprovisedFlooring.IFMagazineCarpet1");
table.insert(ProceduralDistributions.list["DeskGeneric"].items, 0.1);
table.insert(ProceduralDistributions.list["FactoryLockers"].items, "ImprovisedFlooring.IFMagazineCarpet1");
table.insert(ProceduralDistributions.list["FactoryLockers"].items, 1);
table.insert(ProceduralDistributions.list["GigamartHousewares"].items, "ImprovisedFlooring.IFMagazineCarpet1");
table.insert(ProceduralDistributions.list["GigamartHousewares"].items, 6);
table.insert(ProceduralDistributions.list["KitchenBook"].items, "ImprovisedFlooring.IFMagazineCarpet1");
table.insert(ProceduralDistributions.list["KitchenBook"].items, 0.1);
table.insert(ProceduralDistributions.list["LibraryCounter"].items, "ImprovisedFlooring.IFMagazineCarpet1");
table.insert(ProceduralDistributions.list["LibraryCounter"].items, 2);
table.insert(ProceduralDistributions.list["LivingRoomShelf"].items, "ImprovisedFlooring.IFMagazineCarpet1");
table.insert(ProceduralDistributions.list["LivingRoomShelf"].items, 1);
table.insert(ProceduralDistributions.list["MagazineRackMixed"].items, "ImprovisedFlooring.IFMagazineCarpet1");
table.insert(ProceduralDistributions.list["MagazineRackMixed"].items, 1);
table.insert(ProceduralDistributions.list["OfficeDeskHome"].items, "ImprovisedFlooring.IFMagazineCarpet1");
table.insert(ProceduralDistributions.list["OfficeDeskHome"].items, 1);
table.insert(ProceduralDistributions.list["PostOfficeMagazines"].items, "ImprovisedFlooring.IFMagazineCarpet1");
table.insert(ProceduralDistributions.list["PostOfficeMagazines"].items, 1);
table.insert(ProceduralDistributions.list["ShelfGeneric"].items, "ImprovisedFlooring.IFMagazineCarpet1");
table.insert(ProceduralDistributions.list["ShelfGeneric"].items, 0.1);
table.insert(ProceduralDistributions.list["ToolStoreBooks"].items, "ImprovisedFlooring.IFMagazineCarpet1");
table.insert(ProceduralDistributions.list["ToolStoreBooks"].items, 2);

-- Special 1 (Mall)
table.insert(ProceduralDistributions.list["CrateBooks"].items, "ImprovisedFlooring.IFMagazineSpecial1");
table.insert(ProceduralDistributions.list["CrateBooks"].items, 0.5);
table.insert(ProceduralDistributions.list["CrateMagazines"].items, "ImprovisedFlooring.IFMagazineSpecial1");
table.insert(ProceduralDistributions.list["CrateMagazines"].items, 0.5);
table.insert(ProceduralDistributions.list["FactoryLockers"].items, "ImprovisedFlooring.IFMagazineSpecial1");
table.insert(ProceduralDistributions.list["FactoryLockers"].items, 2);
table.insert(ProceduralDistributions.list["LibraryCounter"].items, "ImprovisedFlooring.IFMagazineSpecial1");
table.insert(ProceduralDistributions.list["LibraryCounter"].items, 1);
table.insert(ProceduralDistributions.list["LivingRoomShelf"].items, "ImprovisedFlooring.IFMagazineSpecial1");
table.insert(ProceduralDistributions.list["LivingRoomShelf"].items, 0.1);
table.insert(ProceduralDistributions.list["MagazineRackMixed"].items, "ImprovisedFlooring.IFMagazineSpecial1");
table.insert(ProceduralDistributions.list["MagazineRackMixed"].items, 0.1);
table.insert(ProceduralDistributions.list["MechanicShelfBooks"].items, "ImprovisedFlooring.IFMagazineSpecial1");
table.insert(ProceduralDistributions.list["MechanicShelfBooks"].items, 2);
table.insert(ProceduralDistributions.list["MetalShopTools"].items, "ImprovisedFlooring.IFMagazineSpecial1");
table.insert(ProceduralDistributions.list["MetalShopTools"].items, 1);
table.insert(ProceduralDistributions.list["OfficeDeskHome"].items, "ImprovisedFlooring.IFMagazineSpecial1");
table.insert(ProceduralDistributions.list["OfficeDeskHome"].items, 0.5);
table.insert(ProceduralDistributions.list["ToolStoreBooks"].items, "ImprovisedFlooring.IFMagazineSpecial1");
table.insert(ProceduralDistributions.list["ToolStoreBooks"].items, 0.5);

-- Special 2 (Spiffo)
table.insert(ProceduralDistributions.list["BurgerKitchenButcher"].items, "ImprovisedFlooring.IFMagazineSpecial2");
table.insert(ProceduralDistributions.list["BurgerKitchenButcher"].items, 3);
table.insert(ProceduralDistributions.list["CrateBooks"].items, "ImprovisedFlooring.IFMagazineSpecial2");
table.insert(ProceduralDistributions.list["CrateBooks"].items, 0.5);
table.insert(ProceduralDistributions.list["CrateSpiffoMerch"].items, "ImprovisedFlooring.IFMagazineSpecial2");
table.insert(ProceduralDistributions.list["CrateSpiffoMerch"].items, 10);
table.insert(ProceduralDistributions.list["FactoryLockers"].items, "ImprovisedFlooring.IFMagazineSpecial2");
table.insert(ProceduralDistributions.list["FactoryLockers"].items, 2);
table.insert(ProceduralDistributions.list["FilingCabinetGeneric"].items, "ImprovisedFlooring.IFMagazineSpecial2");
table.insert(ProceduralDistributions.list["FilingCabinetGeneric"].items, 0.5);
table.insert(ProceduralDistributions.list["LibraryCounter"].items, "ImprovisedFlooring.IFMagazineSpecial2");
table.insert(ProceduralDistributions.list["LibraryCounter"].items, 0.1);
table.insert(ProceduralDistributions.list["MechanicShelfBooks"].items, "ImprovisedFlooring.IFMagazineSpecial2");
table.insert(ProceduralDistributions.list["MechanicShelfBooks"].items, 0.5);
table.insert(ProceduralDistributions.list["OfficeCounter"].items, "ImprovisedFlooring.IFMagazineSpecial2");
table.insert(ProceduralDistributions.list["OfficeCounter"].items, 1);
table.insert(ProceduralDistributions.list["OfficeDesk"].items, "ImprovisedFlooring.IFMagazineSpecial2");
table.insert(ProceduralDistributions.list["OfficeDesk"].items, 1);
table.insert(ProceduralDistributions.list["OfficeDeskHome"].items, "ImprovisedFlooring.IFMagazineSpecial2");
table.insert(ProceduralDistributions.list["OfficeDeskHome"].items, 0.1);
table.insert(ProceduralDistributions.list["PlankStashMagazine"].items, "ImprovisedFlooring.IFMagazineSpecial2");
table.insert(ProceduralDistributions.list["PlankStashMagazine"].items, 5);
table.insert(ProceduralDistributions.list["SpiffosKitchenCounter"].items, "ImprovisedFlooring.IFMagazineSpecial2");
table.insert(ProceduralDistributions.list["SpiffosKitchenCounter"].items, 10);

-- Special 3 (Pizza Wirled)
table.insert(ProceduralDistributions.list["CrateBooks"].items, "ImprovisedFlooring.IFMagazineSpecial3");
table.insert(ProceduralDistributions.list["CrateBooks"].items, 0.5);
table.insert(ProceduralDistributions.list["FactoryLockers"].items, "ImprovisedFlooring.IFMagazineSpecial3");
table.insert(ProceduralDistributions.list["FactoryLockers"].items, 2);
table.insert(ProceduralDistributions.list["FilingCabinetGeneric"].items, "ImprovisedFlooring.IFMagazineSpecial3");
table.insert(ProceduralDistributions.list["FilingCabinetGeneric"].items, 0.5);
table.insert(ProceduralDistributions.list["ItalianKitchenButcher"].items, "ImprovisedFlooring.IFMagazineSpecial3");
table.insert(ProceduralDistributions.list["ItalianKitchenButcher"].items, 3);
table.insert(ProceduralDistributions.list["LibraryCounter"].items, "ImprovisedFlooring.IFMagazineSpecial3");
table.insert(ProceduralDistributions.list["LibraryCounter"].items, 0.1);
table.insert(ProceduralDistributions.list["MechanicShelfBooks"].items, "ImprovisedFlooring.IFMagazineSpecial3");
table.insert(ProceduralDistributions.list["MechanicShelfBooks"].items, 0.5);
table.insert(ProceduralDistributions.list["OfficeCounter"].items, "ImprovisedFlooring.IFMagazineSpecial3");
table.insert(ProceduralDistributions.list["OfficeCounter"].items, 1);
table.insert(ProceduralDistributions.list["OfficeDesk"].items, "ImprovisedFlooring.IFMagazineSpecial3");
table.insert(ProceduralDistributions.list["OfficeDesk"].items, 1);
table.insert(ProceduralDistributions.list["OfficeDeskHome"].items, "ImprovisedFlooring.IFMagazineSpecial3");
table.insert(ProceduralDistributions.list["OfficeDeskHome"].items, 0.1);
table.insert(ProceduralDistributions.list["PizzaKitchenButcher"].items, "ImprovisedFlooring.IFMagazineSpecial3");
table.insert(ProceduralDistributions.list["PizzaKitchenButcher"].items, 3);
table.insert(ProceduralDistributions.list["PlankStashMagazine"].items, "ImprovisedFlooring.IFMagazineSpecial3");
table.insert(ProceduralDistributions.list["PlankStashMagazine"].items, 5);

-- Special 4 (Fossoil)
table.insert(ProceduralDistributions.list["CrateBooks"].items, "ImprovisedFlooring.IFMagazineSpecial4");
table.insert(ProceduralDistributions.list["CrateBooks"].items, 0.5);
table.insert(ProceduralDistributions.list["FactoryLockers"].items, "ImprovisedFlooring.IFMagazineSpecial4");
table.insert(ProceduralDistributions.list["FactoryLockers"].items, 2);
table.insert(ProceduralDistributions.list["FilingCabinetGeneric"].items, "ImprovisedFlooring.IFMagazineSpecial4");
table.insert(ProceduralDistributions.list["FilingCabinetGeneric"].items, 0.5);
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "ImprovisedFlooring.IFMagazineSpecial4");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.5);
table.insert(ProceduralDistributions.list["MechanicShelfBooks"].items, "ImprovisedFlooring.IFMagazineSpecial4");
table.insert(ProceduralDistributions.list["MechanicShelfBooks"].items, 0.7);
table.insert(ProceduralDistributions.list["OfficeCounter"].items, "ImprovisedFlooring.IFMagazineSpecial4");
table.insert(ProceduralDistributions.list["OfficeCounter"].items, 1);
table.insert(ProceduralDistributions.list["OfficeDeskHome"].items, "ImprovisedFlooring.IFMagazineSpecial4");
table.insert(ProceduralDistributions.list["OfficeDeskHome"].items, 0.1);
table.insert(ProceduralDistributions.list["PlankStashMagazine"].items, "ImprovisedFlooring.IFMagazineSpecial4");
table.insert(ProceduralDistributions.list["PlankStashMagazine"].items, 2);
table.insert(ProceduralDistributions.list["PostOfficeMagazines"].items, "ImprovisedFlooring.IFMagazineSpecial4");
table.insert(ProceduralDistributions.list["PostOfficeMagazines"].items, 0.5);

-- Tiles 1
table.insert(ProceduralDistributions.list["BookstoreMisc"].items, "ImprovisedFlooring.IFMagazineTiles1");
table.insert(ProceduralDistributions.list["BookstoreMisc"].items, 3);
table.insert(ProceduralDistributions.list["CrateBooks"].items, "ImprovisedFlooring.IFMagazineTiles1");
table.insert(ProceduralDistributions.list["CrateBooks"].items, 6);
table.insert(ProceduralDistributions.list["CrateConcrete"].items, "ImprovisedFlooring.IFMagazineTiles1");
table.insert(ProceduralDistributions.list["CrateConcrete"].items, 5);
table.insert(ProceduralDistributions.list["CrateMagazines"].items, "ImprovisedFlooring.IFMagazineTiles1");
table.insert(ProceduralDistributions.list["CrateMagazines"].items, 1);
table.insert(ProceduralDistributions.list["FactoryLockers"].items, "ImprovisedFlooring.IFMagazineTiles1");
table.insert(ProceduralDistributions.list["FactoryLockers"].items, 1);
table.insert(ProceduralDistributions.list["LibraryCounter"].items, "ImprovisedFlooring.IFMagazineTiles1");
table.insert(ProceduralDistributions.list["LibraryCounter"].items, 2);
table.insert(ProceduralDistributions.list["LivingRoomShelf"].items, "ImprovisedFlooring.IFMagazineTiles1");
table.insert(ProceduralDistributions.list["LivingRoomShelf"].items, 1);
table.insert(ProceduralDistributions.list["MagazineRackMixed"].items, "ImprovisedFlooring.IFMagazineTiles1");
table.insert(ProceduralDistributions.list["MagazineRackMixed"].items, 1);
table.insert(ProceduralDistributions.list["OfficeDeskHome"].items, "ImprovisedFlooring.IFMagazineTiles1");
table.insert(ProceduralDistributions.list["OfficeDeskHome"].items, 1);
table.insert(ProceduralDistributions.list["PostOfficeMagazines"].items, "ImprovisedFlooring.IFMagazineTiles1");
table.insert(ProceduralDistributions.list["PostOfficeMagazines"].items, 1);
table.insert(ProceduralDistributions.list["ShelfGeneric"].items, "ImprovisedFlooring.IFMagazineTiles1");
table.insert(ProceduralDistributions.list["ShelfGeneric"].items, 0.1);
table.insert(ProceduralDistributions.list["ToolStoreBooks"].items, "ImprovisedFlooring.IFMagazineTiles1");
table.insert(ProceduralDistributions.list["ToolStoreBooks"].items, 2);

-- Tiles 2
table.insert(ProceduralDistributions.list["BookstoreMisc"].items, "ImprovisedFlooring.IFMagazineTiles2");
table.insert(ProceduralDistributions.list["BookstoreMisc"].items, 3);
table.insert(ProceduralDistributions.list["CrateBooks"].items, "ImprovisedFlooring.IFMagazineTiles2");
table.insert(ProceduralDistributions.list["CrateBooks"].items, 4);
table.insert(ProceduralDistributions.list["CrateConcrete"].items, "ImprovisedFlooring.IFMagazineTiles2");
table.insert(ProceduralDistributions.list["CrateConcrete"].items, 5);
table.insert(ProceduralDistributions.list["CrateMagazines"].items, "ImprovisedFlooring.IFMagazineTiles2");
table.insert(ProceduralDistributions.list["CrateMagazines"].items, 1);
table.insert(ProceduralDistributions.list["FactoryLockers"].items, "ImprovisedFlooring.IFMagazineTiles2");
table.insert(ProceduralDistributions.list["FactoryLockers"].items, 1);
table.insert(ProceduralDistributions.list["LibraryCounter"].items, "ImprovisedFlooring.IFMagazineTiles2");
table.insert(ProceduralDistributions.list["LibraryCounter"].items, 2);
table.insert(ProceduralDistributions.list["LivingRoomShelf"].items, "ImprovisedFlooring.IFMagazineTiles2");
table.insert(ProceduralDistributions.list["LivingRoomShelf"].items, 1);
table.insert(ProceduralDistributions.list["MagazineRackMixed"].items, "ImprovisedFlooring.IFMagazineTiles2");
table.insert(ProceduralDistributions.list["MagazineRackMixed"].items, 1);
table.insert(ProceduralDistributions.list["OfficeDeskHome"].items, "ImprovisedFlooring.IFMagazineTiles2");
table.insert(ProceduralDistributions.list["OfficeDeskHome"].items, 1);
table.insert(ProceduralDistributions.list["PostOfficeMagazines"].items, "ImprovisedFlooring.IFMagazineTiles2");
table.insert(ProceduralDistributions.list["PostOfficeMagazines"].items, 1);
table.insert(ProceduralDistributions.list["ShelfGeneric"].items, "ImprovisedFlooring.IFMagazineTiles2");
table.insert(ProceduralDistributions.list["ShelfGeneric"].items, 0.1);
table.insert(ProceduralDistributions.list["ToolStoreBooks"].items, "ImprovisedFlooring.IFMagazineTiles2");
table.insert(ProceduralDistributions.list["ToolStoreBooks"].items, 2);

-- Tiles 3
table.insert(ProceduralDistributions.list["BookstoreMisc"].items, "ImprovisedFlooring.IFMagazineTiles3");
table.insert(ProceduralDistributions.list["BookstoreMisc"].items, 3);
table.insert(ProceduralDistributions.list["CrateBooks"].items, "ImprovisedFlooring.IFMagazineTiles3");
table.insert(ProceduralDistributions.list["CrateBooks"].items, 4);
table.insert(ProceduralDistributions.list["CrateConcrete"].items, "ImprovisedFlooring.IFMagazineTiles3");
table.insert(ProceduralDistributions.list["CrateConcrete"].items, 5);
table.insert(ProceduralDistributions.list["CrateMagazines"].items, "ImprovisedFlooring.IFMagazineTiles3");
table.insert(ProceduralDistributions.list["CrateMagazines"].items, 1);
table.insert(ProceduralDistributions.list["FactoryLockers"].items, "ImprovisedFlooring.IFMagazineTiles3");
table.insert(ProceduralDistributions.list["FactoryLockers"].items, 1);
table.insert(ProceduralDistributions.list["LibraryCounter"].items, "ImprovisedFlooring.IFMagazineTiles3");
table.insert(ProceduralDistributions.list["LibraryCounter"].items, 2);
table.insert(ProceduralDistributions.list["LivingRoomShelf"].items, "ImprovisedFlooring.IFMagazineTiles3");
table.insert(ProceduralDistributions.list["LivingRoomShelf"].items, 1);
table.insert(ProceduralDistributions.list["MagazineRackMixed"].items, "ImprovisedFlooring.IFMagazineTiles3");
table.insert(ProceduralDistributions.list["MagazineRackMixed"].items, 1);
table.insert(ProceduralDistributions.list["OfficeDeskHome"].items, "ImprovisedFlooring.IFMagazineTiles3");
table.insert(ProceduralDistributions.list["OfficeDeskHome"].items, 1);
table.insert(ProceduralDistributions.list["PostOfficeMagazines"].items, "ImprovisedFlooring.IFMagazineTiles3");
table.insert(ProceduralDistributions.list["PostOfficeMagazines"].items, 1);
table.insert(ProceduralDistributions.list["ShelfGeneric"].items, "ImprovisedFlooring.IFMagazineTiles3");
table.insert(ProceduralDistributions.list["ShelfGeneric"].items, 0.1);
table.insert(ProceduralDistributions.list["ToolStoreBooks"].items, "ImprovisedFlooring.IFMagazineTiles3");
table.insert(ProceduralDistributions.list["ToolStoreBooks"].items, 2);

-- Wood 1
table.insert(ProceduralDistributions.list["BookstoreMisc"].items, "ImprovisedFlooring.IFMagazineWood1");
table.insert(ProceduralDistributions.list["BookstoreMisc"].items, 3);
table.insert(ProceduralDistributions.list["CabinetFactoryTools"].items, "ImprovisedFlooring.IFMagazineWood1");
table.insert(ProceduralDistributions.list["CabinetFactoryTools"].items, 8);
table.insert(ProceduralDistributions.list["CrateBooks"].items, "ImprovisedFlooring.IFMagazineWood1");
table.insert(ProceduralDistributions.list["CrateBooks"].items, 6);
table.insert(ProceduralDistributions.list["CrateCarpentry"].items, "ImprovisedFlooring.IFMagazineWood1");
table.insert(ProceduralDistributions.list["CrateCarpentry"].items, 4);
table.insert(ProceduralDistributions.list["CrateLumber"].items, "ImprovisedFlooring.IFMagazineWood1");
table.insert(ProceduralDistributions.list["CrateLumber"].items, 8);
table.insert(ProceduralDistributions.list["CrateMagazines"].items, "ImprovisedFlooring.IFMagazineWood1");
table.insert(ProceduralDistributions.list["CrateMagazines"].items, 1);
table.insert(ProceduralDistributions.list["DeskGeneric"].items, "ImprovisedFlooring.IFMagazineWood1");
table.insert(ProceduralDistributions.list["DeskGeneric"].items, 0.05);
table.insert(ProceduralDistributions.list["FactoryLockers"].items, "ImprovisedFlooring.IFMagazineWood1");
table.insert(ProceduralDistributions.list["FactoryLockers"].items, 1);
table.insert(ProceduralDistributions.list["GarageCarpentry"].items, "ImprovisedFlooring.IFMagazineWood1");
table.insert(ProceduralDistributions.list["GarageCarpentry"].items, 4);
table.insert(ProceduralDistributions.list["KitchenBook"].items, "ImprovisedFlooring.IFMagazineWood1");
table.insert(ProceduralDistributions.list["KitchenBook"].items, 0.1);
table.insert(ProceduralDistributions.list["LibraryCounter"].items, "ImprovisedFlooring.IFMagazineWood1");
table.insert(ProceduralDistributions.list["LibraryCounter"].items, 2);
table.insert(ProceduralDistributions.list["LivingRoomShelf"].items, "ImprovisedFlooring.IFMagazineWood1");
table.insert(ProceduralDistributions.list["LivingRoomShelf"].items, 1);
table.insert(ProceduralDistributions.list["MagazineRackMixed"].items, "ImprovisedFlooring.IFMagazineWood1");
table.insert(ProceduralDistributions.list["MagazineRackMixed"].items, 1);
table.insert(ProceduralDistributions.list["OfficeDeskHome"].items, "ImprovisedFlooring.IFMagazineWood1");
table.insert(ProceduralDistributions.list["OfficeDeskHome"].items, 1);
table.insert(ProceduralDistributions.list["PostOfficeMagazines"].items, "ImprovisedFlooring.IFMagazineWood1");
table.insert(ProceduralDistributions.list["PostOfficeMagazines"].items, 1);
table.insert(ProceduralDistributions.list["ShelfGeneric"].items, "ImprovisedFlooring.IFMagazineWood1");
table.insert(ProceduralDistributions.list["ShelfGeneric"].items, 0.1);
table.insert(ProceduralDistributions.list["ToolStoreBooks"].items, "ImprovisedFlooring.IFMagazineWood1");
table.insert(ProceduralDistributions.list["ToolStoreBooks"].items, 2);
