require 'Items/ProceduralDistributions'

-- DEBUG MODE
-- table.insert(ProceduralDistributions.list["BookstoreBooks"].items, "ImprovisedFlooring.IFMagazineTiles");
-- table.insert(ProceduralDistributions.list["BookstoreBooks"].items, 1000);
-- table.insert(ProceduralDistributions.list["BookstoreBooks"].items, "ImprovisedFlooring.IFMagazineFranchise");
-- table.insert(ProceduralDistributions.list["BookstoreBooks"].items, 1000);
-- table.insert(ProceduralDistributions.list["BookstoreBooks"].items, "ImprovisedFlooring.IFMagazineGarden");
-- table.insert(ProceduralDistributions.list["BookstoreBooks"].items, 1000);
-- table.insert(ProceduralDistributions.list["BookstoreBooks"].items, "ImprovisedFlooring.IFMagazineIndustrial");
-- table.insert(ProceduralDistributions.list["BookstoreBooks"].items, 1000);
-- table.insert(ProceduralDistributions.list["BookstoreBooks"].items, "ImprovisedFlooring.IFMagazineUrban");
-- table.insert(ProceduralDistributions.list["BookstoreBooks"].items, 1000);
-- table.insert(ProceduralDistributions.list["BookstoreBooks"].items, "ImprovisedFlooring.IFMagazineEasterEgg");
-- table.insert(ProceduralDistributions.list["BookstoreBooks"].items, 1000);

-- IFMagazineTiles (Dave Depot: Tile Catalog)
table.insert(ProceduralDistributions.list["BinGeneric"].items, "ImprovisedFlooring.IFMagazineTiles");
table.insert(ProceduralDistributions.list["BinGeneric"].items, 0.5);
table.insert(ProceduralDistributions.list["BookstoreMisc"].items, "ImprovisedFlooring.IFMagazineTiles");
table.insert(ProceduralDistributions.list["BookstoreMisc"].items, 3);
table.insert(ProceduralDistributions.list["CabinetFactoryTools"].items, "ImprovisedFlooring.IFMagazineTiles");
table.insert(ProceduralDistributions.list["CabinetFactoryTools"].items, 1);
table.insert(ProceduralDistributions.list["CrateBooks"].items, "ImprovisedFlooring.IFMagazineTiles");
table.insert(ProceduralDistributions.list["CrateBooks"].items, 6);
table.insert(ProceduralDistributions.list["CrateCarpentry"].items, "ImprovisedFlooring.IFMagazineTiles");
table.insert(ProceduralDistributions.list["CrateCarpentry"].items, 4);
table.insert(ProceduralDistributions.list["CrateMagazines"].items, "ImprovisedFlooring.IFMagazineTiles");
table.insert(ProceduralDistributions.list["CrateMagazines"].items, 1);
table.insert(ProceduralDistributions.list["CratePlaster"].items, "ImprovisedFlooring.IFMagazineTiles");
table.insert(ProceduralDistributions.list["CratePlaster"].items, 1);
table.insert(ProceduralDistributions.list["CrateRandomJunk"].items, "ImprovisedFlooring.IFMagazineTiles");
table.insert(ProceduralDistributions.list["CrateRandomJunk"].items, 1);
table.insert(ProceduralDistributions.list["CrateTools"].items, "ImprovisedFlooring.IFMagazineTiles");
table.insert(ProceduralDistributions.list["CrateTools"].items, 1);
table.insert(ProceduralDistributions.list["FactoryLockers"].items, "ImprovisedFlooring.IFMagazineTiles");
table.insert(ProceduralDistributions.list["FactoryLockers"].items, 1);
table.insert(ProceduralDistributions.list["GarageCarpentry"].items, "ImprovisedFlooring.IFMagazineTiles");
table.insert(ProceduralDistributions.list["GarageCarpentry"].items, 1);
table.insert(ProceduralDistributions.list["JanitorMisc"].items, "ImprovisedFlooring.IFMagazineTiles");
table.insert(ProceduralDistributions.list["JanitorMisc"].items, 2);
table.insert(ProceduralDistributions.list["LibraryCounter"].items, "ImprovisedFlooring.IFMagazineTiles");
table.insert(ProceduralDistributions.list["LibraryCounter"].items, 2);
table.insert(ProceduralDistributions.list["LivingRoomShelf"].items, "ImprovisedFlooring.IFMagazineTiles");
table.insert(ProceduralDistributions.list["LivingRoomShelf"].items, 1);
table.insert(ProceduralDistributions.list["MagazineRackMixed"].items, "ImprovisedFlooring.IFMagazineTiles");
table.insert(ProceduralDistributions.list["MagazineRackMixed"].items, 1);
table.insert(ProceduralDistributions.list["OfficeDeskHome"].items, "ImprovisedFlooring.IFMagazineTiles");
table.insert(ProceduralDistributions.list["OfficeDeskHome"].items, 1);
table.insert(ProceduralDistributions.list["PlankStashMagazine"].items, "ImprovisedFlooring.IFMagazineTiles");
table.insert(ProceduralDistributions.list["PlankStashMagazine"].items, 1);
table.insert(ProceduralDistributions.list["PostOfficeMagazines"].items, "ImprovisedFlooring.IFMagazineTiles");
table.insert(ProceduralDistributions.list["PostOfficeMagazines"].items, 1);
table.insert(ProceduralDistributions.list["ShelfGeneric"].items, "ImprovisedFlooring.IFMagazineTiles");
table.insert(ProceduralDistributions.list["ShelfGeneric"].items, 0.1);
table.insert(ProceduralDistributions.list["ToolStoreBooks"].items, "ImprovisedFlooring.IFMagazineTiles");
table.insert(ProceduralDistributions.list["ToolStoreBooks"].items, 2);
table.insert(ProceduralDistributions.list["ToolStoreCarpentry"].items, "ImprovisedFlooring.IFMagazineTiles");
table.insert(ProceduralDistributions.list["ToolStoreCarpentry"].items, 1);

-- IFMagazineFranchise (Franchise Flooring Specifications)
table.insert(ProceduralDistributions.list["BinGeneric"].items, "ImprovisedFlooring.IFMagazineFranchise");
table.insert(ProceduralDistributions.list["BinGeneric"].items, 0.25);
table.insert(ProceduralDistributions.list["BookstoreMisc"].items, "ImprovisedFlooring.IFMagazineFranchise");
table.insert(ProceduralDistributions.list["BookstoreMisc"].items, 1);
table.insert(ProceduralDistributions.list["BreakRoomCounter"].items, "ImprovisedFlooring.IFMagazineFranchise");
table.insert(ProceduralDistributions.list["BreakRoomCounter"].items, 1);
table.insert(ProceduralDistributions.list["CrateBooks"].items, "ImprovisedFlooring.IFMagazineFranchise");
table.insert(ProceduralDistributions.list["CrateBooks"].items, 4);
table.insert(ProceduralDistributions.list["CrateMagazines"].items, "ImprovisedFlooring.IFMagazineFranchise");
table.insert(ProceduralDistributions.list["CrateMagazines"].items, 1);
table.insert(ProceduralDistributions.list["CrateOfficeChairs"].items, "ImprovisedFlooring.IFMagazineFranchise");
table.insert(ProceduralDistributions.list["CrateOfficeChairs"].items, 10);
table.insert(ProceduralDistributions.list["CrateOfficeSupplies"].items, "ImprovisedFlooring.IFMagazineFranchise");
table.insert(ProceduralDistributions.list["CrateOfficeSupplies"].items, 1);
table.insert(ProceduralDistributions.list["CrateRandomJunk"].items, "ImprovisedFlooring.IFMagazineFranchise");
table.insert(ProceduralDistributions.list["CrateRandomJunk"].items, 1);
table.insert(ProceduralDistributions.list["CrateSpiffoMerch"].items, "ImprovisedFlooring.IFMagazineFranchise");
table.insert(ProceduralDistributions.list["CrateSpiffoMerch"].items, 1);
table.insert(ProceduralDistributions.list["EngineerTools"].items, "ImprovisedFlooring.IFMagazineFranchise");
table.insert(ProceduralDistributions.list["EngineerTools"].items, 2);
table.insert(ProceduralDistributions.list["FilingCabinetGeneric"].items, "ImprovisedFlooring.IFMagazineFranchise");
table.insert(ProceduralDistributions.list["FilingCabinetGeneric"].items, 5);
table.insert(ProceduralDistributions.list["LibraryCounter"].items, "ImprovisedFlooring.IFMagazineFranchise");
table.insert(ProceduralDistributions.list["LibraryCounter"].items, 2);
table.insert(ProceduralDistributions.list["MagazineRackMixed"].items, "ImprovisedFlooring.IFMagazineFranchise");
table.insert(ProceduralDistributions.list["MagazineRackMixed"].items, 1);
table.insert(ProceduralDistributions.list["OfficeDesk"].items, "ImprovisedFlooring.IFMagazineFranchise");
table.insert(ProceduralDistributions.list["OfficeDesk"].items, 1);
table.insert(ProceduralDistributions.list["OfficeDeskHome"].items, "ImprovisedFlooring.IFMagazineFranchise");
table.insert(ProceduralDistributions.list["OfficeDeskHome"].items, 1);
table.insert(ProceduralDistributions.list["PlankStashMagazine"].items, "ImprovisedFlooring.IFMagazineFranchise");
table.insert(ProceduralDistributions.list["PlankStashMagazine"].items, 1);
table.insert(ProceduralDistributions.list["PostOfficeMagazines"].items, "ImprovisedFlooring.IFMagazineFranchise");
table.insert(ProceduralDistributions.list["PostOfficeMagazines"].items, 1);
table.insert(ProceduralDistributions.list["ShelfGeneric"].items, "ImprovisedFlooring.IFMagazineFranchise");
table.insert(ProceduralDistributions.list["ShelfGeneric"].items, 0.1);
table.insert(ProceduralDistributions.list["ToolStoreBooks"].items, "ImprovisedFlooring.IFMagazineFranchise");
table.insert(ProceduralDistributions.list["ToolStoreBooks"].items, 2);
table.insert(ProceduralDistributions.list["WardrobeManClassy"].items, "ImprovisedFlooring.IFMagazineFranchise");
table.insert(ProceduralDistributions.list["WardrobeManClassy"].items, 0.01);

-- IFMagazineGarden (Home and Garden)
table.insert(ProceduralDistributions.list["BinGeneric"].items, "ImprovisedFlooring.IFMagazineGarden");
table.insert(ProceduralDistributions.list["BinGeneric"].items, 0.34);
table.insert(ProceduralDistributions.list["BookstoreMisc"].items, "ImprovisedFlooring.IFMagazineGarden");
table.insert(ProceduralDistributions.list["BookstoreMisc"].items, 3);
table.insert(ProceduralDistributions.list["CafeShelfBooks"].items, "ImprovisedFlooring.IFMagazineGarden");
table.insert(ProceduralDistributions.list["CafeShelfBooks"].items, 6);
table.insert(ProceduralDistributions.list["CampingStoreBooks"].items, "ImprovisedFlooring.IFMagazineGarden");
table.insert(ProceduralDistributions.list["CampingStoreBooks"].items, 2);
table.insert(ProceduralDistributions.list["CrateBooks"].items, "ImprovisedFlooring.IFMagazineGarden");
table.insert(ProceduralDistributions.list["CrateBooks"].items, 5);
table.insert(ProceduralDistributions.list["CrateCamping"].items, "ImprovisedFlooring.IFMagazineGarden");
table.insert(ProceduralDistributions.list["CrateCamping"].items, 0.5);
table.insert(ProceduralDistributions.list["CrateFarming"].items, "ImprovisedFlooring.IFMagazineGarden");
table.insert(ProceduralDistributions.list["CrateFarming"].items, 2);
table.insert(ProceduralDistributions.list["CrateMagazines"].items, "ImprovisedFlooring.IFMagazineGarden");
table.insert(ProceduralDistributions.list["CrateMagazines"].items, 1);
table.insert(ProceduralDistributions.list["CrateRandomJunk"].items, "ImprovisedFlooring.IFMagazineGarden");
table.insert(ProceduralDistributions.list["CrateRandomJunk"].items, 1);
table.insert(ProceduralDistributions.list["CrateTools"].items, "ImprovisedFlooring.IFMagazineGarden");
table.insert(ProceduralDistributions.list["CrateTools"].items, 1);
table.insert(ProceduralDistributions.list["GardenStoreMisc"].items, "ImprovisedFlooring.IFMagazineGarden");
table.insert(ProceduralDistributions.list["GardenStoreMisc"].items, 6);
table.insert(ProceduralDistributions.list["GigamartFarming"].items, "ImprovisedFlooring.IFMagazineGarden");
table.insert(ProceduralDistributions.list["GigamartFarming"].items, 5);
table.insert(ProceduralDistributions.list["KitchenRandom"].items, "ImprovisedFlooring.IFMagazineGarden");
table.insert(ProceduralDistributions.list["KitchenRandom"].items, 0.5);
table.insert(ProceduralDistributions.list["LibraryCounter"].items, "ImprovisedFlooring.IFMagazineGarden");
table.insert(ProceduralDistributions.list["LibraryCounter"].items, 2);
table.insert(ProceduralDistributions.list["LivingRoomShelf"].items, "ImprovisedFlooring.IFMagazineGarden");
table.insert(ProceduralDistributions.list["LivingRoomShelf"].items, 1);
table.insert(ProceduralDistributions.list["MagazineRackMixed"].items, "ImprovisedFlooring.IFMagazineGarden");
table.insert(ProceduralDistributions.list["MagazineRackMixed"].items, 1);
table.insert(ProceduralDistributions.list["PlankStashMagazine"].items, "ImprovisedFlooring.IFMagazineGarden");
table.insert(ProceduralDistributions.list["PlankStashMagazine"].items, 1);
table.insert(ProceduralDistributions.list["PostOfficeMagazines"].items, "ImprovisedFlooring.IFMagazineGarden");
table.insert(ProceduralDistributions.list["PostOfficeMagazines"].items, 1);
table.insert(ProceduralDistributions.list["PrisonCellRandom"].items, "ImprovisedFlooring.IFMagazineGarden");
table.insert(ProceduralDistributions.list["PrisonCellRandom"].items, 0.1);
table.insert(ProceduralDistributions.list["ShelfGeneric"].items, "ImprovisedFlooring.IFMagazineGarden");
table.insert(ProceduralDistributions.list["ShelfGeneric"].items, 0.1);
table.insert(ProceduralDistributions.list["ToolStoreBooks"].items, "ImprovisedFlooring.IFMagazineGarden");
table.insert(ProceduralDistributions.list["ToolStoreBooks"].items, 2);
table.insert(ProceduralDistributions.list["ToolStoreFarming"].items, "ImprovisedFlooring.IFMagazineGarden");
table.insert(ProceduralDistributions.list["ToolStoreFarming"].items, 1);
table.insert(ProceduralDistributions.list["WardrobeWomanClassy"].items, "ImprovisedFlooring.IFMagazineGarden");
table.insert(ProceduralDistributions.list["WardrobeWomanClassy"].items, 0.01);

-- IFMagazineIndustrial (Industrial flooring and design)
table.insert(ProceduralDistributions.list["BinGeneric"].items, "ImprovisedFlooring.IFMagazineIndustrial");
table.insert(ProceduralDistributions.list["BinGeneric"].items, 0.1);
table.insert(ProceduralDistributions.list["BookstoreMisc"].items, "ImprovisedFlooring.IFMagazineIndustrial");
table.insert(ProceduralDistributions.list["BookstoreMisc"].items, 1);
table.insert(ProceduralDistributions.list["CrateBooks"].items, "ImprovisedFlooring.IFMagazineIndustrial");
table.insert(ProceduralDistributions.list["CrateBooks"].items, 3);
table.insert(ProceduralDistributions.list["CrateIndustrialSinks"].items, "ImprovisedFlooring.IFMagazineIndustrial");
table.insert(ProceduralDistributions.list["CrateIndustrialSinks"].items, 10);
table.insert(ProceduralDistributions.list["CrateMagazines"].items, "ImprovisedFlooring.IFMagazineIndustrial");
table.insert(ProceduralDistributions.list["CrateMagazines"].items, 1);
table.insert(ProceduralDistributions.list["CrateOfficeSupplies"].items, "ImprovisedFlooring.IFMagazineIndustrial");
table.insert(ProceduralDistributions.list["CrateOfficeSupplies"].items, 1);
table.insert(ProceduralDistributions.list["CrateRandomJunk"].items, "ImprovisedFlooring.IFMagazineIndustrial");
table.insert(ProceduralDistributions.list["CrateRandomJunk"].items, 1);
table.insert(ProceduralDistributions.list["CrateTools"].items, "ImprovisedFlooring.IFMagazineIndustrial");
table.insert(ProceduralDistributions.list["CrateTools"].items, 1);
table.insert(ProceduralDistributions.list["ElectronicStoreMagazines"].items, "ImprovisedFlooring.IFMagazineIndustrial");
table.insert(ProceduralDistributions.list["ElectronicStoreMagazines"].items, 1);
table.insert(ProceduralDistributions.list["EngineerTools"].items, "ImprovisedFlooring.IFMagazineIndustrial");
table.insert(ProceduralDistributions.list["EngineerTools"].items, 2);
table.insert(ProceduralDistributions.list["FactoryLockers"].items, "ImprovisedFlooring.IFMagazineIndustrial");
table.insert(ProceduralDistributions.list["FactoryLockers"].items, 1);
table.insert(ProceduralDistributions.list["GigamartTools"].items, "ImprovisedFlooring.IFMagazineIndustrial");
table.insert(ProceduralDistributions.list["GigamartTools"].items, 1);
table.insert(ProceduralDistributions.list["JanitorMisc"].items, "ImprovisedFlooring.IFMagazineIndustrial");
table.insert(ProceduralDistributions.list["JanitorMisc"].items, 2);
table.insert(ProceduralDistributions.list["LibraryCounter"].items, "ImprovisedFlooring.IFMagazineIndustrial");
table.insert(ProceduralDistributions.list["LibraryCounter"].items, 2);
table.insert(ProceduralDistributions.list["MagazineRackMixed"].items, "ImprovisedFlooring.IFMagazineIndustrial");
table.insert(ProceduralDistributions.list["MagazineRackMixed"].items, 1);
table.insert(ProceduralDistributions.list["MedicalStorageTools"].items, "ImprovisedFlooring.IFMagazineIndustrial");
table.insert(ProceduralDistributions.list["MedicalStorageTools"].items, 1);
table.insert(ProceduralDistributions.list["OfficeDesk"].items, "ImprovisedFlooring.IFMagazineIndustrial");
table.insert(ProceduralDistributions.list["OfficeDesk"].items, 1);
table.insert(ProceduralDistributions.list["PlankStashMagazine"].items, "ImprovisedFlooring.IFMagazineIndustrial");
table.insert(ProceduralDistributions.list["PlankStashMagazine"].items, 1);
table.insert(ProceduralDistributions.list["PostOfficeMagazines"].items, "ImprovisedFlooring.IFMagazineIndustrial");
table.insert(ProceduralDistributions.list["PostOfficeMagazines"].items, 1);
table.insert(ProceduralDistributions.list["ShelfGeneric"].items, "ImprovisedFlooring.IFMagazineIndustrial");
table.insert(ProceduralDistributions.list["ShelfGeneric"].items, 0.1);
table.insert(ProceduralDistributions.list["StoreCounterCleaning"].items, "ImprovisedFlooring.IFMagazineIndustrial");
table.insert(ProceduralDistributions.list["StoreCounterCleaning"].items, 0.5);
table.insert(ProceduralDistributions.list["ToolStoreBooks"].items, "ImprovisedFlooring.IFMagazineIndustrial");
table.insert(ProceduralDistributions.list["ToolStoreBooks"].items, 2);
table.insert(ProceduralDistributions.list["WardrobeRedneck"].items, "ImprovisedFlooring.IFMagazineIndustrial");
table.insert(ProceduralDistributions.list["WardrobeRedneck"].items, 0.01);

-- IFMagazineUrban (Urban Walkways and Roads)
table.insert(ProceduralDistributions.list["BinGeneric"].items, "ImprovisedFlooring.IFMagazineUrban");
table.insert(ProceduralDistributions.list["BinGeneric"].items, 0.1);
table.insert(ProceduralDistributions.list["BookstoreMisc"].items, "ImprovisedFlooring.IFMagazineUrban");
table.insert(ProceduralDistributions.list["BookstoreMisc"].items, 2);
table.insert(ProceduralDistributions.list["ClassroomShelves"].items, "ImprovisedFlooring.IFMagazineUrban");
table.insert(ProceduralDistributions.list["ClassroomShelves"].items, 1);
table.insert(ProceduralDistributions.list["CrateBooks"].items, "ImprovisedFlooring.IFMagazineUrban");
table.insert(ProceduralDistributions.list["CrateBooks"].items, 4);
table.insert(ProceduralDistributions.list["CrateConcrete"].items, "ImprovisedFlooring.IFMagazineUrban");
table.insert(ProceduralDistributions.list["CrateConcrete"].items, 5);
table.insert(ProceduralDistributions.list["CrateMagazines"].items, "ImprovisedFlooring.IFMagazineUrban");
table.insert(ProceduralDistributions.list["CrateMagazines"].items, 1);
table.insert(ProceduralDistributions.list["CrateRandomJunk"].items, "ImprovisedFlooring.IFMagazineUrban");
table.insert(ProceduralDistributions.list["CrateRandomJunk"].items, 1);
table.insert(ProceduralDistributions.list["CrateTools"].items, "ImprovisedFlooring.IFMagazineUrban");
table.insert(ProceduralDistributions.list["CrateTools"].items, 1);
table.insert(ProceduralDistributions.list["FireDeptLockers"].items, "ImprovisedFlooring.IFMagazineUrban");
table.insert(ProceduralDistributions.list["FireDeptLockers"].items, 0.5);
table.insert(ProceduralDistributions.list["LibraryCounter"].items, "ImprovisedFlooring.IFMagazineUrban");
table.insert(ProceduralDistributions.list["LibraryCounter"].items, 2);
table.insert(ProceduralDistributions.list["MagazineRackMixed"].items, "ImprovisedFlooring.IFMagazineUrban");
table.insert(ProceduralDistributions.list["MagazineRackMixed"].items, 1);
table.insert(ProceduralDistributions.list["MechanicShelfBooks"].items, "ImprovisedFlooring.IFMagazineUrban");
table.insert(ProceduralDistributions.list["MechanicShelfBooks"].items, 2);
table.insert(ProceduralDistributions.list["MetalShopTools"].items, "ImprovisedFlooring.IFMagazineUrban");
table.insert(ProceduralDistributions.list["MetalShopTools"].items, 2);
table.insert(ProceduralDistributions.list["PlankStashMagazine"].items, "ImprovisedFlooring.IFMagazineUrban");
table.insert(ProceduralDistributions.list["PlankStashMagazine"].items, 1);
table.insert(ProceduralDistributions.list["PostOfficeMagazines"].items, "ImprovisedFlooring.IFMagazineUrban");
table.insert(ProceduralDistributions.list["PostOfficeMagazines"].items, 1);
table.insert(ProceduralDistributions.list["ShelfGeneric"].items, "ImprovisedFlooring.IFMagazineUrban");
table.insert(ProceduralDistributions.list["ShelfGeneric"].items, 0.1);
table.insert(ProceduralDistributions.list["ToolStoreBooks"].items, "ImprovisedFlooring.IFMagazineUrban");
table.insert(ProceduralDistributions.list["ToolStoreBooks"].items, 2);

-- IFMagazineEasterEgg (Nostalgic Carpet)
table.insert(ProceduralDistributions.list["DaycareCounter"].items, "ImprovisedFlooring.IFMagazineEasteEgg");
table.insert(ProceduralDistributions.list["DaycareCounter"].items, 0.01);
table.insert(ProceduralDistributions.list["DaycareShelves"].items, "ImprovisedFlooring.IFMagazineEasteEgg");
table.insert(ProceduralDistributions.list["DaycareShelves"].items, 0.01);
table.insert(ProceduralDistributions.list["GigamartToys"].items, "ImprovisedFlooring.IFMagazineEasteEgg");
table.insert(ProceduralDistributions.list["GigamartToys"].items, 0.01);
